version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5000:5000"  # Expose port for frontend (adjust if needed)
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5001:5000"  # Expose port for backend API
    environment:
      - DATABASE_URL=sqlite:///app.db  # Adjust for your DB configuration